version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
  - package-ecosystem: "npm"
    directory: "backend/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
  - package-ecosystem: "maven"
    directory: "keycloak-extension/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
