version: "3.8"

services:
  nginx:
    image: nginx
    hostname: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/oasismap-local.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    command: ["--version"]

